#!/bin/bash

serialDevicePattern="/dev/ttyUSB*"
serialDevices=( $serialDevicePattern )
serialDevice="${serialDevices[0]}"

echo "serial device detected at $serialDevice"

sudo docker run -t -i -u esp \
--device=$serialDevice \
-v /home/mint/Projects/esp8266/nodemcu:/home/esp/shared_project \
tavk/esp-sdk:0.1.0 \
esptool.py --port $serialDevice \
erase_flash
